ARG ruby_version
ARG node_version
FROM ruby:${ruby_version}-alpine3.11

ARG BUILD_DATE
ARG REVISION_SHA

LABEL org.opencontainers.image.created=$BUILD_DATE \
  org.opencontainers.image.authors="dev@northpass.com" \
  org.opencontainers.image.source="https://github.com/SchoolKeep/dockerfiles" \
  org.opencontainers.image.revision=$REVISION_SHA \
  org.opencontainers.image.vendor="Northpass" \
  org.opencontainers.image.title="Northpass Development Base Image" \
  org.opencontainers.image.description="Base image used to run Northpass in development and test envs"

COPY --from=node:${node_version}-alpine3.11 / /

RUN apk update && \
    apk upgrade && \
    apk add --update --no-cache \
    bash \
    build-base \
    ca-certificates \
    cairo-dev \
    coreutils \
    curl \
    curl-dev \
    giflib-dev \
    git \
    jpeg-dev \
    less \
    ncurses \
    openssh \
    openssl \
    pango-dev \
    postgresql-client \
    postgresql-dev \
    python \
    tzdata \
    yaml-dev \
    xvfb \
    zlib-dev

ENV NODE_ENV=development DOCKERIZE_VERSION=v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /app

RUN mkdir -p -m 0600 ~/.ssh && \
      ssh-keyscan github.com >> ~/.ssh/known_hosts && \
      gem install bundler -v=2.1.4 && \
      bundle config --global --jobs $(nproc) && \
      yarn --version
