FROM ruby:2.5.3-alpine

LABEL org.opencontainers.image.created=$BUILD_DATE \
  org.opencontainers.image.authors="dev@northpass.com" \
  org.opencontainers.image.source="https://github.com/SchoolKeep/dockerfiles" \
  org.opencontainers.image.revision=$REVISION_SHA \
  org.opencontainers.image.vendor="Northpass" \
  org.opencontainers.image.title="Northpass Development Base Image" \
  org.opencontainers.image.description="Base image used to run Northpass in development and test envs"

COPY --from=node:10.15.3-alpine / /

RUN apk update && \
    apk upgrade && \
    apk add --update --no-cache \
    build-base \
    ca-certificates \
    cairo-dev \
    curl \
    curl-dev \
    giflib-dev \
    git \
    jpeg-dev \
    openssh \
    pango-dev \
    postgresql-client \
    postgresql-dev \
    python \
    tzdata \
    yaml-dev \
    zlib-dev

ENV NODE_ENV=development BUNDLE_PATH=/bundle

WORKDIR /app

RUN mkdir -p -m 0600 ~/.ssh && \
      ssh-keyscan github.com >> ~/.ssh/known_hosts && \
      gem install bundler -v=2.1.4 && \
      bundle config --global --jobs $(nproc) && \
      npm install -g yarn
