version: 2.1

jobs:
  build_and_push:
    parameters:
      cypress_version:
        type: string
        default: 5.1.0
      ruby_version:
        type: string
        default: 2.5.8
    working_directory: ~/dockerfiles
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: |
            docker build -f Dockerfile.dev \
              --build-arg BUILD_DATE="$(date '+%Y-%m-%dT%H:%M:%S')" \
              --build-arg REVISION_SHA=$CIRCLE_SHA1 \
              --build-arg ruby_version=<< parameters.ruby_version >> \
              -t "northpass/base-dev:<< parameters.ruby_version >>" \
              .
            docker build -f Dockerfile.cypress \
              --build-arg BUILD_DATE="$(date '+%Y-%m-%dT%H:%M:%S')" \
              --build-arg REVISION_SHA=$CIRCLE_SHA1 \
              --build-arg CYPRESS_VERSION=<< parameters.cypress_version >> \
              -t "northpass/base-cypress:latest" \
              -t "northpass/base-cypress:<< parameters.cypress_version >>" \
              .
      - run:
          name: Push image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login --username "$DOCKER_HUB_LOGIN" --password-stdin
            docker push northpass/base-dev
            docker push northpass/base-cypress

workflows:
  build_and_push:
    jobs:
      - build_and_push:
          ruby_version: 2.5.8
          context: docker-hub
          filters:
            branches:
              only:
                - master
      - build_and_push:
          ruby_version: 2.7.2
          context: docker-hub
          filters:
            branches:
              only:
                - master
  scheduled_build_and_push:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - build_and_push:
          ruby_version: 2.5.8
          context: docker-hub
      - build_and_push:
          ruby_version: 2.7.2
          context: docker-hub
