version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build_and_push:
    working_directory: ~/dockerfiles
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile.dev
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "latest,${CIRCLE_SHA1}"

workflows:
  build_and_push:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master
