version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build_test:
    working_directory: ~/dockerfiles
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile.test
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "latest,test,${CIRCLE_SHA1}"
  build_dev:
    working_directory: ~/dockerfiles
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile.development
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "latest,development,${CIRCLE_SHA1}"

workflows:
  build-and-publish:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - master
      - build_test:
          filters:
            branches:
              only:
                - master
