version: 2.1

jobs:
  build_and_push:
    working_directory: ~/dockerfiles
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: |
            docker build \
              -t base-dev:latest \
              -t base-dev:$CIRCLE_SHA1 \
              --build-arg BUILD_DATE=$(date '+%d/%m/%Y %H:%M:%S') \
              --build-arg REVISION_SHA=$CIRCLE_SHA1 \
              -f Dockerfile.dev
              .
      - run:
          name: Push image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
            docker push base-dev:latest

workflows:
  build_and_push:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master
